# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.cache/wt [current_project]
set_property parent.project_path C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/characters.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/teclas.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/hello_world.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/ps2_read_ms.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/clk_divider.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/pianito.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/driver_vga.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/kbd_ms.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/lab6_prev_2.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/cursor.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/teclado_to_note.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/teclado.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/segmentos.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/record_to_display.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/music.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/mostrar.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/memoria.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/display.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/clk_divider_2.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/graphics.v
  C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/new/top_module.v
}
read_ip -quiet C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/JavierTorres/Documents/GitHub/proyecto_final/proyecto_final.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/JavierTorres/Documents/GitHub/proyecto_final/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/JavierTorres/Documents/GitHub/proyecto_final/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_module -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
